AllCops:
  TargetRubyVersion: 2.4
  UseCache: false
  DisplayCopNames: true
Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
  Enabled: true
